// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFeQaT8apfXK51DGU7TMoFs9Q1sBLLNyM',
    appId: '1:32871131800:web:24211b7781632a8fe57eed',
    messagingSenderId: '32871131800',
    projectId: 'aniguess-project',
    authDomain: 'aniguess-project.firebaseapp.com',
    storageBucket: 'aniguess-project.firebasestorage.app',
    measurementId: 'G-M54BZ6SZZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVxzLk6XTD0ZftnsLIJVJjVm6UYMv-FUE',
    appId: '1:32871131800:android:aa190bc7c06e7956e57eed',
    messagingSenderId: '32871131800',
    projectId: 'aniguess-project',
    storageBucket: 'aniguess-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzG20Zg0tIAzscyuOVv3xAnmeqp6M5SIY',
    appId: '1:32871131800:ios:844d3fbd906490b9e57eed',
    messagingSenderId: '32871131800',
    projectId: 'aniguess-project',
    storageBucket: 'aniguess-project.firebasestorage.app',
    iosBundleId: 'com.example.animeQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzG20Zg0tIAzscyuOVv3xAnmeqp6M5SIY',
    appId: '1:32871131800:ios:844d3fbd906490b9e57eed',
    messagingSenderId: '32871131800',
    projectId: 'aniguess-project',
    storageBucket: 'aniguess-project.firebasestorage.app',
    iosBundleId: 'com.example.animeQuiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFeQaT8apfXK51DGU7TMoFs9Q1sBLLNyM',
    appId: '1:32871131800:web:27edcf7ad0a3cc31e57eed',
    messagingSenderId: '32871131800',
    projectId: 'aniguess-project',
    authDomain: 'aniguess-project.firebaseapp.com',
    storageBucket: 'aniguess-project.firebasestorage.app',
    measurementId: 'G-N9RDK204BG',
  );

}